export const data = {
  aka: [{ record: { firstName: 'ab', akaUnit: 'sf1', status: 'lala' } }],
  eightSocks: [
    {
      record: {
        tz: '47115165',
        stype: 'D',
        mi: '47115165',
        firstName: 'Elmo',
        lastName: 'Blanda',
        entity: 'digimon',
        rnk: null,
        rld: null,
        birthday: '1997-07-20T14:59:47.468Z',
        phone: '8037542',
        areaCode: '54',
        hr: 'iste/numquam/enim',
        tf: 'Specialist',
        userName: 'Elmo.Blanda52',
        mail: 'Elmo.Blanda52@jello.com',
        location: 'Customer Integration Executive',
      },
    },
  ],
  sf: [
    {
      record: {
        firstName: 'Elvera',
        lastName: 'Sanford',
        userName: 'Elvera15',
        fullName: 'Elvera Sanford',
        sex: 'fds',
        personalNumber: '875334308',
        tz: '77522631',
        stype: 'B',
        hierarchy: ['sapiente', 'dolor', 'vero', 'dolorem', 'accusamus'],
        mail: 'Hilton72@.com',
        rank: 'champion',
        status: 'active',
        address: '40917 Kelsie Springs Apt. 574',
        telephone: '0504215627',
        entity: 'soldier',
        discharge: '2030-02-17T04:14:48.804Z',
        primaryDU: { uniqueID: 'Hilton72', adfsUID: 'Hilton72@ddd' },
      },
    },
  ],
  city: [
    {
      record: {
        domUser: 'e835789651@turtle.com',
        telephone: '0594849368',
        clearance: 5,
        firstName: 'Ashlynn',
        lastName: 'Sporer',
        mail: 'לא ידוע',
        tz: '49204662',
        personalNumber: 'לא ידוע',
        rank: 'ultimate',
        rld: null,
        job: 'District Infrastructure Consultant',
        profession: '',
        department: 'city5',
        stype: '',
        hr: 'Ashlynn Sporer',
        company: '',
        isPortalUser: false,
        tags: [],
        domains: ['external', 'local'],
        displayName: 'string',
        entityType: 'string',
        identityCard: 'string',
        status: 'string',
        dischargeDay: 'Date',
        phone: 'string',
        mobilePhone: 'string',
        address: 'string',
        pictures: {
          profile: {
            url: 'string',
            meta: 'any',
          },
        },
        sex: 'string',
        birthDate: 'Date',
        createdAt: 'Date',
        updatedAt: 'Date',
      },
    },
  ],
  adNn: [
    {
      record: {
        KfirstName: 'Elvera',
        guName: 'Elvera',
        KlastName: 'Sanford',
        userPrincipalName: 'D61902573',
        Kjob: 'Corporate Accounts Assistant',
        hierarchy: 'officiis/similique/architecto/Corporate Accounts Assistant - Elvera Sanford',
        sAMAccountName: 'Geovanni_Stamm',
        mail: 'Geovanni_Stamm@rabiran.com',
      },
    },
  ],
  adS: [
    {
      record: {
        KfirstName: 'Amaya',
        guName: 'Amaya',
        KlastName: 'Lang',
        userPrincipalName: 'D32447362',
        Kjob: 'Principal Mobility Consultant',
        hierarchy: 'tenetur/dolor/vitae/Principal Mobility Consultant - Amaya Lang',
        sAMAccountName: 'Ardella_Yundt',
        mail: 'Ardella_Yundt@rabiran.com',
      },
    },
  ],

  identifiers: {
    personalNumber: '207226568',
    identityCard: '8112005',
    goalUser: '',
  },
};
